#!/usr/bin/env bash
#using while for hours and minutes to diplay
hour=0
while [ $hour -le 12 ]
do
     echo "Hour: $hour"
     minute=1
     while [ $minute -le 59 ]
     do
         echo "$minute"
         ((minute++))
      done
      ((hour++))
  done
