#!/usr/bin/env bash
#using if and else
#script on school file
filename="school"
if [ -e $filename ]; then
   echo "school file exists"
   if [ ! -s $filename ]; then
      echo "school file exists"
   else
      echo "school file is not empty"
   fi
   if [ -f $filename ]; then
      echo "school is a regular file"
   done
else
   echo "school file does not exist"
done
